<?php

declare(strict_types=1);

/*
 * HackNHustleIONDIDLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace HackNHustleIONDIDLib\Tests;

use Core\Types\CallbackCatcher;

class ClientFactory
{
    public static function create(CallbackCatcher $httpCallback): \HackNHustleIONDIDLib\HackNHustleIONDIDClient
    {
        $clientBuilder = \HackNHustleIONDIDLib\HackNHustleIONDIDClientBuilder::init();
        $clientBuilder = self::addConfigurationFromEnvironment($clientBuilder);
        $clientBuilder = self::addTestConfiguration($clientBuilder);
        return $clientBuilder->httpCallback($httpCallback)->build();
    }

    public static function addTestConfiguration(
        \HackNHustleIONDIDLib\HackNHustleIONDIDClientBuilder $builder
    ): \HackNHustleIONDIDLib\HackNHustleIONDIDClientBuilder {
        return $builder;
    }

    public static function addConfigurationFromEnvironment(
        \HackNHustleIONDIDLib\HackNHustleIONDIDClientBuilder $builder
    ): \HackNHustleIONDIDLib\HackNHustleIONDIDClientBuilder {
        $timeout = getenv('HACK_N_HUSTLE_IONDID_LIB_TIMEOUT');
        $numberOfRetries = getenv('HACK_N_HUSTLE_IONDID_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('HACK_N_HUSTLE_IONDID_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('HACK_N_HUSTLE_IONDID_LIB_ENVIRONMENT');

        if ($timeout !== false && \is_numeric($timeout)) {
            $builder->timeout(intval($timeout));
        }

        if ($numberOfRetries !== false && \is_numeric($numberOfRetries)) {
            $builder->numberOfRetries(intval($numberOfRetries));
        }

        if ($maximumRetryWaitTime !== false && \is_numeric($maximumRetryWaitTime)) {
            $builder->maximumRetryWaitTime(intval($maximumRetryWaitTime));
        }

        if ($environment !== false) {
            $builder->environment($environment);
        }

        return $builder;
    }
}
