<?php

declare(strict_types=1);

/*
 * HackNHustleIONDIDLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace HackNHustleIONDIDLib\Models;

use stdClass;

class CreateSignRequest implements \JsonSerializable
{
    /**
     * @var Message
     */
    private $message;

    /**
     * @var PrivateKey
     */
    private $privateKey;

    /**
     * @param Message $message
     * @param PrivateKey $privateKey
     */
    public function __construct(Message $message, PrivateKey $privateKey)
    {
        $this->message = $message;
        $this->privateKey = $privateKey;
    }

    /**
     * Returns Message.
     */
    public function getMessage(): Message
    {
        return $this->message;
    }

    /**
     * Sets Message.
     *
     * @required
     * @maps message
     */
    public function setMessage(Message $message): void
    {
        $this->message = $message;
    }

    /**
     * Returns Private Key.
     */
    public function getPrivateKey(): PrivateKey
    {
        return $this->privateKey;
    }

    /**
     * Sets Private Key.
     *
     * @required
     * @maps private_key
     */
    public function setPrivateKey(PrivateKey $privateKey): void
    {
        $this->privateKey = $privateKey;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['message']     = $this->message;
        $json['private_key'] = $this->privateKey;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
