<?php

declare(strict_types=1);

/*
 * HackNHustleIONDIDLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace HackNHustleIONDIDLib\Models;

use stdClass;

class CredentialSubject implements \JsonSerializable
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var License
     */
    private $license;

    /**
     * @param string $id
     * @param License $license
     */
    public function __construct(string $id, License $license)
    {
        $this->id = $id;
        $this->license = $license;
    }

    /**
     * Returns Id.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns License.
     */
    public function getLicense(): License
    {
        return $this->license;
    }

    /**
     * Sets License.
     *
     * @required
     * @maps License
     */
    public function setLicense(License $license): void
    {
        $this->license = $license;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']      = $this->id;
        $json['License'] = $this->license;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
