<?php

declare(strict_types=1);

/*
 * HackNHustleIONDIDLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace HackNHustleIONDIDLib\Models;

use stdClass;

class License implements \JsonSerializable
{
    /**
     * @var string
     */
    private $type;

    /**
     * @var string
     */
    private $dLNumber;

    /**
     * @param string $type
     * @param string $dLNumber
     */
    public function __construct(string $type, string $dLNumber)
    {
        $this->type = $type;
        $this->dLNumber = $dLNumber;
    }

    /**
     * Returns Type.
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     *
     * @required
     * @maps type
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns D L Number.
     */
    public function getDLNumber(): string
    {
        return $this->dLNumber;
    }

    /**
     * Sets D L Number.
     *
     * @required
     * @maps DLNumber
     */
    public function setDLNumber(string $dLNumber): void
    {
        $this->dLNumber = $dLNumber;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['type']     = $this->type;
        $json['DLNumber'] = $this->dLNumber;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
