<?php

declare(strict_types=1);

/*
 * HackNHustleIONDIDLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace HackNHustleIONDIDLib\Models;

use stdClass;

class Message implements \JsonSerializable
{
    /**
     * @var string
     */
    private $mobileNumber;

    /**
     * @param string $mobileNumber
     */
    public function __construct(string $mobileNumber)
    {
        $this->mobileNumber = $mobileNumber;
    }

    /**
     * Returns Mobile Number.
     */
    public function getMobileNumber(): string
    {
        return $this->mobileNumber;
    }

    /**
     * Sets Mobile Number.
     *
     * @required
     * @maps Mobile Number
     */
    public function setMobileNumber(string $mobileNumber): void
    {
        $this->mobileNumber = $mobileNumber;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['Mobile Number'] = $this->mobileNumber;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
