<?php

declare(strict_types=1);

/*
 * HackNHustleIONDIDLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace HackNHustleIONDIDLib\Models;

use stdClass;

class QRCodeRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $name;

    /**
     * @var int
     */
    private $age;

    /**
     * @var string
     */
    private $department;

    /**
     * @var string
     */
    private $id;

    /**
     * @param string $name
     * @param int $age
     * @param string $department
     * @param string $id
     */
    public function __construct(string $name, int $age, string $department, string $id)
    {
        $this->name = $name;
        $this->age = $age;
        $this->department = $department;
        $this->id = $id;
    }

    /**
     * Returns Name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Age.
     */
    public function getAge(): int
    {
        return $this->age;
    }

    /**
     * Sets Age.
     *
     * @required
     * @maps age
     */
    public function setAge(int $age): void
    {
        $this->age = $age;
    }

    /**
     * Returns Department.
     */
    public function getDepartment(): string
    {
        return $this->department;
    }

    /**
     * Sets Department.
     *
     * @required
     * @maps department
     */
    public function setDepartment(string $department): void
    {
        $this->department = $department;
    }

    /**
     * Returns Id.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['name']       = $this->name;
        $json['age']        = $this->age;
        $json['department'] = $this->department;
        $json['id']         = $this->id;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
