<?php

declare(strict_types=1);

/*
 * HackNHustleIONDIDLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace HackNHustleIONDIDLib\Models;

use stdClass;

class VerifySignRequest implements \JsonSerializable
{
    /**
     * @var PublicKey
     */
    private $publicKey;

    /**
     * @param PublicKey $publicKey
     */
    public function __construct(PublicKey $publicKey)
    {
        $this->publicKey = $publicKey;
    }

    /**
     * Returns Public Key.
     */
    public function getPublicKey(): PublicKey
    {
        return $this->publicKey;
    }

    /**
     * Sets Public Key.
     *
     * @required
     * @maps public_key
     */
    public function setPublicKey(PublicKey $publicKey): void
    {
        $this->publicKey = $publicKey;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['public_key'] = $this->publicKey;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
